name: MyFirstPlugin
version: '${project.version}'
main: me.heymydude.myfirstplugin.MyFirstPlugin
api-version: 1.18
commands:
  god:
    description: Become invincible
    usage: /<command>

  wand:
    description: Become invincible
    usage: /<command>
    aliases:
      - wand

  die:
    description: Become invincible
    usage: //<command>
    aliases:
      - begone